### ISSUE TITLE
hello,  there are some error when run "python3 run.py self"

### ISSUE THREAD

**Issue by gamersover** [NeymarL/ChineseChess-AlphaZero#21]
018-08-26 10:09:03,172@cchess_alphazero.agent.api ERROR # EOF error: 
Exception in thread prediction_worker:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fly/cetrol_workspace/ChineseChess-AlphaZero-distributed/cchess_alphazero/agent/api.py", line 50, in predict_batch_worker
    while pipe.poll():
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed

it's looks like a thread problem, but i don't know how to slove it.

**Comment by NeymarL** [comment]
Please list the full information of the output.

**Comment by gamersover** [comment]
用公司的windows没有报错，但是用学校的linux报错
环境ubuntu16.04，tensorflow版本1.3.0
Using TensorFlow backend.
2018-08-28 20:14:57.389075: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-28 20:14:57.389107: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-28 20:14:57.389112: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-08-28 20:14:57.389116: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-08-28 20:14:57.389120: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-08-28 20:14:57.560302: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-28 20:14:57.560671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:01:00.0
Total memory: 10.91GiB
Free memory: 10.42GiB
2018-08-28 20:14:57.560684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-08-28 20:14:57.560688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-08-28 20:14:57.560706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)
2018-08-28 20:14:57,561@cchess_alphazero.agent.model DEBUG # loading model from /home/fly/cetrol_workspace/ChineseChess-AlphaZero-distributed/data/model/model_best_config.json
2018-08-28 20:14:59,795@cchess_alphazero.agent.model DEBUG # loaded model digest = 72bc0f439dfc12a7adc87065294591206f08986529950b99303d2a7ecadaaee1
2018-08-28 20:14:59,806@cchess_alphazero.worker.self_play DEBUG # Initialize selfplay worker
2018-08-28 20:15:09,818@cchess_alphazero.worker.self_play DEBUG # Selfplay#Start Process index = 0, pid = 17943
2018-08-28 20:17:23,374@cchess_alphazero.worker.self_play INFO # 闲着循环三次，作和棋处理
2018-08-28 20:17:23,542@cchess_alphazero.worker.self_play INFO # Process 17943 save play data to /home/fly/cetrol_workspace/ChineseChess-AlphaZero-distributed/data/play_data/play_20180828-201723.542866.json
2018-08-28 20:17:23,558@cchess_alphazero.agent.api ERROR # EOF error: 
Exception in thread prediction_worker:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fly/cetrol_workspace/ChineseChess-AlphaZero-distributed/cchess_alphazero/agent/api.py", line 50, in predict_batch_worker
    while pipe.poll():
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed

swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.

**Comment by NeymarL** [comment]
是每次都这样吗，程序是跑完一局才崩溃的，可能是遇到了什么特殊情况，多试几次看看

**Comment by gamersover** [comment]
是的，每一次都这样，我尝试过了很多次，不知道为啥

**Comment by NeymarL** [comment]
你运行的命令是什么呢

**Comment by gamersover** [comment]
python3 run.py self

**Comment by NeymarL** [comment]
换成 `python3 colaboratory/run.py [用户名] [进程数]`

**Comment by gamersover** [comment]
好，回去试试
