### ISSUE TITLE
Failed to execute script play_games

### ISSUE THREAD

**Issue by lsplsplsp1111** [NeymarL/ChineseChess-AlphaZero#43]
Traceback (most recent call last):
  File "play_games.py", line 43, in <module>
  File "cchess_alphazero\play_games\play.py", line 37, in start
  File "cchess_alphazero\play_games\play.py", line 107, in start
  File "cchess_alphazero\play_games\play.py", line 82, in init_screen
OSError: unable to read font file 'D:\桌面的文件\play_games-gpu-cuda8\play_games\cchess_alphazero\play_games\PingFang.ttc'
[13948] Failed to execute script play_games

**Comment by liuxilu** [comment]
## READ THE README

**Note**: Before you start, you need to download/find a font file (`.ttc`) and rename it as `PingFang.ttc`, then put it into `cchess_alphazero/play_games`. I have removed the font file from this repo because it's too big, but you can download it from [here](http://alphazero.52coding.com.cn/PingFang.ttc).

**Comment by zhangshuhui241** [comment]
不一定需要专门下载ttc文件。大多数人的/windows/fonts/目录下就有.ttc文件，我就是在这里面随便找了一个mingliu.ttc的文件，拷贝到/cchess_alphazero/play_games目录下，然后改名为PingFang.ttc，就可以正常运行了
