### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\象棋AI\\ChineseChess-AlphaZero\\cchess_alphazero\\play_games\\PingFang.ttc'

### ISSUE THREAD

**Issue by gc1024zc** [NeymarL/ChineseChess-AlphaZero#67]
Using CPU version
(CCZero) D:\象棋AI\ChineseChess-AlphaZero>python cchess_alphazero/run.py play
2022-07-20 02:46:43,360@cchess_alphazero.manager INFO # Config type: mini
pygame 2.1.2 (SDL 2.0.18, Python 3.6.15)
Hello from the pygame community. https://www.pygame.org/contribute.html
D:\anaconda3\envs\CCZero\lib\site-packages\tensorflow\python\framework\dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\anaconda3\envs\CCZero\lib\site-packages\tensorflow\python\framework\dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\anaconda3\envs\CCZero\lib\site-packages\tensorflow\python\framework\dtypes.py:460: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\anaconda3\envs\CCZero\lib\site-packages\tensorflow\python\framework\dtypes.py:461: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\anaconda3\envs\CCZero\lib\site-packages\tensorflow\python\framework\dtypes.py:462: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\anaconda3\envs\CCZero\lib\site-packages\tensorflow\python\framework\dtypes.py:465: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
2022-07-20 02:47:02,548@cchess_alphazero.manager INFO # AI move first : False
2022-07-20 02:47:02,550@cchess_alphazero.agent.model DEBUG # loading model from D:\象棋AI\ChineseChess-AlphaZero\data\model\model_best_config.json
2022-07-20 02:47:04.096894: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2022-07-20 02:47:04.097207: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2022-07-20 02:47:04,485@cchess_alphazero.agent.model DEBUG # loaded model digest = b14704b8970f4b178deb5cac44d7ca16c75f2dbb267d88b856a8d22d7c9fc96b
Traceback (most recent call last):
  File "cchess_alphazero/run.py", line 14, in <module>
    manager.start()
  File "D:\象棋AI\ChineseChess-AlphaZero\cchess_alphazero\manager.py", line 93, in start
    play.start(config, not args.ai_move_first)
  File "D:\象棋AI\ChineseChess-AlphaZero\cchess_alphazero\play_games\play.py", line 36, in start
    play.start(human_move_first)
  File "D:\象棋AI\ChineseChess-AlphaZero\cchess_alphazero\play_games\play.py", line 107, in start
    screen, board_background, widget_background = self.init_screen()
  File "D:\象棋AI\ChineseChess-AlphaZero\cchess_alphazero\play_games\play.py", line 82, in init_screen
    font = pygame.font.Font(font_file, 16)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\象棋AI\\ChineseChess-AlphaZero\\cchess_alphazero\\play_games\\PingFang.ttc'

**Comment by charleschen2006** [comment]
我也遇到了，是少了一个字体么？

**Comment by BigStupideer** [comment]
READ ME里面有写，注意去下载一下。如果是MAC电脑的话，可以直接从这里复制/System/Library/Fonts

**Comment by BigStupideer** [comment]
> 我也遇到了，是少了一个字体么？


READ ME里面有写，注意去下载一下。如果是MAC电脑的话，可以直接从这里复制/System/Library/Fonts

**Comment by BigStupideer** [comment]
READ ME里面有写，注意去下载一下。如果是MAC电脑的话，可以直接从这里复制/System/Library/Fonts
