### ISSUE TITLE
在单卡的机器上怎么跑sl，提示出错

### ISSUE THREAD

**Issue by charleschen2006** [NeymarL/ChineseChess-AlphaZero#69]
2022-11-14 13:22:02.083125: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x22b8770 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-11-14 13:22:02.083144: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 4090, Compute Capability 8.9
Traceback (most recent call last):
  File "cchess_alphazero/run.py", line 14, in <module>
    manager.start()
  File "/home/charles/ChineseChess-One/cchess_alphazero/manager.py", line 100, in start
    sl.start(config)
  File "/home/charles/ChineseChess-One/cchess_alphazero/worker/sl.py", line 31, in start
    set_session_config(per_process_gpu_memory_fraction=1, allow_growth=True, device_list='0,1')
  File "/home/charles/ChineseChess-One/cchess_alphazero/lib/tf_util.py", line 20, in set_session_config
    sess = tf.Session(config=config)
  File "/home/charles/.local/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1585, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/charles/.local/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 699, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid device ordinal value (1). Valid range is [0, 0].

我已经使用了参数 --gpu ‘0’ ，命令： python cchess_alphazero/run.py sl --gpu '0'

**Comment by charleschen2006** [comment]
已解决 作者是用的双卡
